total_mapping = {
    "Total T\xe9rmico": "Thermal",
    "Total E\xf3lico": "Wind",
    "Total Hidroel\xe9ctrica": "Hydro",
    "Total Solar": "Solar",
    "Total Generado": "Generated",
}

# Power plant types
# http://www.sie.gob.do/images/Estadisticas/MEM/GeneracionDiariaEnero2017/
# Reporte_diario_de_generacion_31_enero_2017_merged2.pdf

thermal_plants = {
    "AES ANDRES": "gas",
    "BARAHONA CARBON": "coal",
    "BERSAL": "oil",
    "CEPP 1": "oil",
    "CEPP 2": "oil",
    "CESPM 1 FO": "oil",
    "CESPM 1 GN": "gas",
    "CESPM 2 FO": "oil",
    "CESPM 2 GN": "gas",
    "CESPM 3 FO": "oil",
    "CESPM 3 GN": "gas",
    "ESTRELLA DEL MAR 2 CFO": "oil",
    "ESTRELLA DEL MAR 2 CGN": "gas",
    "ESTRELLA DEL MAR 2 SFO": "oil",
    "ESTRELLA DEL MAR 2 SGN": "gas",
    "ESTRELLA DEL MAR 3": "gas",
    "GENERACI\xD3N DE EMERGENCIA AES ANDR\xC9S": "gas",
    "HAINA TG": "oil",
    "INCA KM22": "oil",
    "ITABO 1": "coal",
    "ITABO 2": "coal",
    "LA VEGA": "oil",
    "LOS MINA 5": "gas",
    "LOS MINA 6": "gas",
    "LOS MINA 7": "gas",
    "LOS OR\xcdGENES POWER PLANT FUEL OIL": "oil",
    "LOS OR\xcdGENES POWER PLANT GAS NATURAL": "gas",
    "METALDOM": "oil",
    "MONTE RIO": "oil",
    "PALAMARA": "oil",
    "PALENQUE": "oil",
    "PARQUE ENERGETICO LOS MINA CC PARCIAL": "gas",
    "PARQUE ENERGETICO LOS MINA CC TOTAL": "gas",
    "PIMENTEL 1": "oil",
    "PIMENTEL 2": "oil",
    "PIMENTEL 3": "oil",
    "PUNTA CATALINA 1": "coal",
    "PUNTA CATALINA 2": "coal",
    "QUISQUEYA 1B SAN PEDRO GN": "gas",
    "QUISQUEYA 1 FO": "oil",
    "QUISQUEYA 1 GN": "gas",
    "QUISQUEYA 2 FO": "oil",
    "QUISQUEYA 2 GN": "gas",
    "QUISQUEYA 1 SAN PEDRO FO": "oil",
    "QUISQUEYA 1 SAN PEDRO GN": "gas",
    "RIO SAN JUAN": "oil",
    "SAN FELIPE": "oil",
    "SAN FELIPE CC": "gas",
    "SAN FELIPE VAP": "oil",
    "SAN LORENZO 1": "gas",
    "SAN PEDRO BIO-ENERGY": "biomass",
    "SAN PEDRO VAPOR": "oil",
    "SULTANA DEL ESTE": "oil",
}
